export interface SharedFigure {
  fig_id: number;
  cat: string;
  quote: string | null;
  qattr: string | null;
}

// Auto-generated from src/lib/figuresData.js — keep in sync.
export const FIGURES: SharedFigure[] = [
  {"fig_id":1,"cat":"khans","quote":"Би бол тэнгэрийн шийтгэл. Хэрэв та нар нүгэл үйлдээгүй бол тэнгэр намайг танд илгээхгүй байсан.","qattr":"Чингис Хаан"},
  {"fig_id":2,"cat":"khans","quote":null,"qattr":null},
  {"fig_id":3,"cat":"khans","quote":"Ялагдлаас суралцдаггүй хүн хэзээ ч ялж чадахгүй.","qattr":"Хубилай Хаан"},
  {"fig_id":4,"cat":"khans","quote":"Гарын хурган адилгүй байдагтай адил, Тэнгэр хүмүүст янз бүрийн зам өгсөн байна.","qattr":"Мөнх Хаан"},
  {"fig_id":5,"cat":"khans","quote":null,"qattr":null},
  {"fig_id":6,"cat":"khans","quote":null,"qattr":null},
  {"fig_id":7,"cat":"khans","quote":null,"qattr":null},
  {"fig_id":8,"cat":"khans","quote":null,"qattr":null},
  {"fig_id":9,"cat":"khans","quote":null,"qattr":null},
  {"fig_id":10,"cat":"khans","quote":null,"qattr":null},
  {"fig_id":11,"cat":"khans","quote":null,"qattr":null},
  {"fig_id":12,"cat":"khans","quote":null,"qattr":null},
  {"fig_id":13,"cat":"khans","quote":null,"qattr":null},
  {"fig_id":14,"cat":"queens","quote":null,"qattr":null},
  {"fig_id":15,"cat":"queens","quote":null,"qattr":null},
  {"fig_id":16,"cat":"queens","quote":null,"qattr":null},
  {"fig_id":17,"cat":"queens","quote":"Нэг сумыг амархан хугалж болно, харин таван сумыг хэзээ ч хугалж чадахгүй.","qattr":"Алан Гоа"},
  {"fig_id":18,"cat":"queens","quote":null,"qattr":null},
  {"fig_id":19,"cat":"queens","quote":null,"qattr":null},
  {"fig_id":20,"cat":"queens","quote":null,"qattr":null},
  {"fig_id":21,"cat":"queens","quote":null,"qattr":null},
  {"fig_id":22,"cat":"queens","quote":null,"qattr":null},
  {"fig_id":23,"cat":"queens","quote":null,"qattr":null},
  {"fig_id":24,"cat":"warriors","quote":null,"qattr":null},
  {"fig_id":25,"cat":"warriors","quote":null,"qattr":null},
  {"fig_id":26,"cat":"warriors","quote":null,"qattr":null},
  {"fig_id":27,"cat":"warriors","quote":null,"qattr":null},
  {"fig_id":28,"cat":"warriors","quote":null,"qattr":null},
  {"fig_id":29,"cat":"warriors","quote":null,"qattr":null},
  {"fig_id":30,"cat":"warriors","quote":null,"qattr":null},
  {"fig_id":31,"cat":"warriors","quote":null,"qattr":null},
  {"fig_id":32,"cat":"warriors","quote":null,"qattr":null},
  {"fig_id":33,"cat":"warriors","quote":null,"qattr":null},
  {"fig_id":34,"cat":"warriors","quote":"Бидний нэгдсэн хүчинд ямар ч дайсан тэсэхгүй.","qattr":"Д. Сүхбаатар"},
  {"fig_id":35,"cat":"warriors","quote":null,"qattr":null},
  {"fig_id":36,"cat":"political","quote":"Эзэнт гүрнийг морин дээрээс байгуулж болно, харин морин дээрээс удирдаж болохгүй.","qattr":"Елүй Чуцай"},
  {"fig_id":37,"cat":"political","quote":null,"qattr":null},
  {"fig_id":38,"cat":"political","quote":null,"qattr":null},
  {"fig_id":39,"cat":"political","quote":null,"qattr":null},
  {"fig_id":40,"cat":"political","quote":null,"qattr":null},
  {"fig_id":41,"cat":"political","quote":null,"qattr":null},
  {"fig_id":42,"cat":"political","quote":null,"qattr":null},
  {"fig_id":43,"cat":"political","quote":null,"qattr":null},
  {"fig_id":44,"cat":"political","quote":null,"qattr":null},
  {"fig_id":45,"cat":"cultural","quote":null,"qattr":null},
  {"fig_id":46,"cat":"cultural","quote":null,"qattr":null},
  {"fig_id":47,"cat":"cultural","quote":null,"qattr":null},
  {"fig_id":48,"cat":"cultural","quote":null,"qattr":null},
  {"fig_id":49,"cat":"cultural","quote":"Миний нутаг, миний нутаг, алтан дэлхийн дээр.","qattr":"Д. Нацагдорж"},
  {"fig_id":50,"cat":"cultural","quote":null,"qattr":null},
  {"fig_id":51,"cat":"cultural","quote":null,"qattr":null},
  {"fig_id":52,"cat":"cultural","quote":null,"qattr":null},
  {"fig_id":53,"cat":"khans","quote":null,"qattr":null},
  {"fig_id":54,"cat":"khans","quote":null,"qattr":null},
  {"fig_id":55,"cat":"khans","quote":null,"qattr":null},
  {"fig_id":56,"cat":"khans","quote":null,"qattr":null},
  {"fig_id":57,"cat":"khans","quote":null,"qattr":null},
  {"fig_id":58,"cat":"khans","quote":null,"qattr":null},
  {"fig_id":59,"cat":"khans","quote":null,"qattr":null},
  {"fig_id":60,"cat":"khans","quote":null,"qattr":null},
  {"fig_id":61,"cat":"khans","quote":null,"qattr":null},
  {"fig_id":62,"cat":"khans","quote":null,"qattr":null},
  {"fig_id":63,"cat":"khans","quote":null,"qattr":null},
  {"fig_id":64,"cat":"khans","quote":null,"qattr":null},
  {"fig_id":65,"cat":"khans","quote":null,"qattr":null},
  {"fig_id":66,"cat":"khans","quote":null,"qattr":null},
  {"fig_id":67,"cat":"khans","quote":null,"qattr":null},
  {"fig_id":68,"cat":"khans","quote":null,"qattr":null},
  {"fig_id":69,"cat":"khans","quote":null,"qattr":null},
  {"fig_id":70,"cat":"khans","quote":null,"qattr":null},
  {"fig_id":71,"cat":"khans","quote":null,"qattr":null},
  {"fig_id":72,"cat":"khans","quote":null,"qattr":null},
  {"fig_id":73,"cat":"khans","quote":null,"qattr":null},
  {"fig_id":74,"cat":"khans","quote":null,"qattr":null},
  {"fig_id":75,"cat":"khans","quote":null,"qattr":null},
  {"fig_id":76,"cat":"khans","quote":null,"qattr":null},
  {"fig_id":77,"cat":"khans","quote":null,"qattr":null},
  {"fig_id":78,"cat":"khans","quote":null,"qattr":null},
  {"fig_id":79,"cat":"khans","quote":null,"qattr":null},
  {"fig_id":80,"cat":"khans","quote":null,"qattr":null},
  {"fig_id":81,"cat":"khans","quote":null,"qattr":null},
  {"fig_id":82,"cat":"khans","quote":null,"qattr":null},
  {"fig_id":83,"cat":"khans","quote":null,"qattr":null}
];
